"""initial schema

Revision ID: 6b8239a7a7eb
Revises: 
Create Date: 2026-06-28 22:39:18.244139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8239a7a7eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('friend', 'parent', 'family', 'other', name='contactkind', native_enum=False, length=16), nullable=False),
    sa.Column('parent_contact_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_contact_id'], ['contact.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('role', sa.Enum('child', 'adult', 'elder', name='role', native_enum=False, length=16), nullable=False),
    sa.Column('bsn', sa.String(length=16), nullable=True),
    sa.Column('huisarts', sa.Text(), nullable=True),
    sa.Column('tandarts', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('due', 'booked', 'done', 'cancelled', name='appointmentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_person_id'), ['person_id'], unique=False)

    op.create_table('contact_person_link',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'person_id')
    )
    op.create_table('recurring_obligation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=False),
    sa.Column('last_done', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_obligation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_obligation_person_id'), ['person_id'], unique=False)

    op.create_table('vaccination_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('vaccine', sa.String(length=120), nullable=False),
    sa.Column('where', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vaccination_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccination_record_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccination_record_person_id'))

    op.drop_table('vaccination_record')
    with op.batch_alter_table('recurring_obligation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_obligation_person_id'))

    op.drop_table('recurring_obligation')
    op.drop_table('contact_person_link')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_person_id'))

    op.drop_table('appointment')
    op.drop_table('person')
    op.drop_table('contact')
    # ### end Alembic commands ###
